(()=>{const sb=window.vibeSupabase,$=id=>document.getElementById(id);let stream=null,channel=null,host=false,peers=new Map(),liveId=null;
const rtc={iceServers:[{urls:'stun:stun.l.google.com:19302'}]};
function status(t){if($('liveStatus'))$('liveStatus').textContent=t}
function open(){const m=$('liveModal');if(m){m.classList.add('open');m.setAttribute('aria-hidden','false');list()}}
function close(){if(host)return alert('Сначала заверши эфир.');$('liveModal')?.classList.remove('open')}
async function user(){return(await sb.auth.getUser()).data?.user||null}
async function list(){const box=$('liveList');if(!box)return;const r=await sb.from('live_streams').select('id,title,host_user_id,viewer_count,created_at').eq('status','live').order('created_at',{ascending:false}).limit(20);if(r.error){box.textContent=r.error.message;return}box.innerHTML=(r.data||[]).map(x=>'<button class="live-item" data-live-id="'+x.id+'">🔴 '+esc(x.title)+' <small>👀 '+x.viewer_count+'</small></button>').join('')||'<small>Ҳоло эфир нест.</small>';box.querySelectorAll('[data-live-id]').forEach(b=>b.onclick=()=>join(b.dataset.liveId))}
function esc(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
async function start(){const u=await user();if(!u)return window.vibe?.toast?.('Сначала войди в VIBE');if(host)return;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:true});$('liveVideo').srcObject=stream;const ins=await sb.from('live_streams').insert({host_user_id:u.id,title:$('liveTitle')?.value.trim()||'Прямой эфир'}).select().single();if(ins.error)throw ins.error;liveId=ins.data.id;host=true;channel=sb.channel('vibe-live-'+liveId,{config:{broadcast:{self:true}}});channel.on('broadcast',{event:'signal'},async({payload})=>{if(payload.to===u.id)return;let pc=peers.get(payload.from);if(!pc){pc=new RTCPeerConnection(rtc);stream.getTracks().forEach(t=>pc.addTrack(t,stream));pc.onicecandidate=e=>e.candidate&&channel.send({type:'broadcast',event:'signal',payload:{from:u.id,to:payload.from,type:'candidate',candidate:e.candidate}});peers.set(payload.from,pc)}if(payload.type==='answer'){await pc.setRemoteDescription(payload.sdp)}else if(payload.type==='candidate'){await pc.addIceCandidate(payload.candidate)}});await channel.subscribe();await channel.send({type:'broadcast',event:'presence',payload:{user_id:u.id}});$('startLiveBtn').style.display='none';$('endLiveBtn').style.display='block';$('joinLiveBtn').style.display='none';status('🔴 LIVE');await list()}catch(e){stream?.getTracks().forEach(t=>t.stop());stream=null;status('Хатогӣ: '+(e.message||e));}}
async function join(id){if(host)return;const u=await user();if(!u)return window.vibe?.toast?.('Сначала войди в VIBE');const r=await sb.from('live_streams').select('*').eq('id',id).eq('status','live').single();if(r.error)return window.vibe?.toast?.(r.error.message);liveId=id;channel=sb.channel('vibe-live-'+id,{config:{broadcast:{self:true}}});const pc=new RTCPeerConnection(rtc);peers.set('host',pc);pc.ontrack=e=>{$('liveVideo').srcObject=e.streams[0];$('liveVideo').muted=false};pc.onicecandidate=e=>e.candidate&&channel.send({type:'broadcast',event:'signal',payload:{from:u.id,to:r.data.host_user_id,type:'candidate',candidate:e.candidate}});channel.on('broadcast',{event:'signal'},async({payload})=>{if(payload.to!==u.id)return;if(payload.type==='offer'){await pc.setRemoteDescription(payload.sdp);const ans=await pc.createAnswer();await pc.setLocalDescription(ans);await channel.send({type:'broadcast',event:'signal',payload:{from:u.id,to:payload.from,type:'answer',sdp:ans}})}else if(payload.type==='candidate'){await pc.addIceCandidate(payload.candidate)}});await channel.subscribe();await channel.send({type:'broadcast',event:'viewer',payload:{user_id:u.id}});status('👀 Тамошо');}
async function end(){if(!host||!liveId)return;const u=await user();await sb.from('live_streams').update({status:'ended',ended_at:new Date().toISOString()}).eq('id',liveId).eq('host_user_id',u.id);peers.forEach(p=>p.close());peers.clear();channel&&sb.removeChannel(channel);stream?.getTracks().forEach(t=>t.stop());stream=null;channel=null;liveId=null;host=false;$('liveVideo').srcObject=null;$('startLiveBtn').style.display='block';$('endLiveBtn').style.display='none';$('joinLiveBtn').style.display='block';status('Завершён');list()}
document.addEventListener('DOMContentLoaded',()=>{$('liveBtn')?.addEventListener('click',open);$('liveClose')?.addEventListener('click',close);$('liveBackdrop')?.addEventListener('click',close);$('startLiveBtn')?.addEventListener('click',start);$('endLiveBtn')?.addEventListener('click',end);$('joinLiveBtn')?.addEventListener('click',list)});window.vibeLive={open,start,end,join}})();